In [ ]:
from __future__ import absolute_import, division, print_function
import numpy as np
import tensorflow as tf



In [ ]:
# Eager execution is enabled by default in TensorFlow 2.x

# Define constant tensors
print("Define constant tensors")
a = tf.constant(2)
print(f"a = {a}")
b = tf.constant(3)
print(f"b = {b}")

Define constant tensors
a = 2
b = 3


In [ ]:
# Run the operation without the need for tf.Session
print("Running operations, without tf.Session")
c = a + b
print(f"a + b = {c}")
d = a * b
print(f"a * b = {d}")

Running operations, without tf.Session
a + b = 5
a * b = 6


In [ ]:
# Full compatibility with Numpy
print("Mixing operations with Tensors and Numpy Arrays")

# Define constant tensors
a = tf.constant([[2., 1.], [1., 0.]], dtype=tf.float32)
print(f"Tensor:\n a = \n{a}")
b = np.array([[3., 0.], [5., 1.]], dtype=np.float32)
print(f"NumpyArray:\n b = \n{b}")

Mixing operations with Tensors and Numpy Arrays
Tensor:
 a = 
[[2. 1.]
 [1. 0.]]
NumpyArray:
 b = 
[[3. 0.]
 [5. 1.]]


In [ ]:
# Run the operation without the need for tf.Session
c = a + b
print(f"a + b = \n{c}")

d = tf.matmul(a, b)
print(f"a * b (Matrix Multiplication) = \n{d}")

a + b = 
[[5. 1.]
 [6. 1.]]
a * b (Matrix Multiplication) = 
[[11.  1.]
 [ 3.  0.]]


In [ ]:
# Iterate through Tensor 'a'
print("Iterate through Tensor 'a':")
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        print(a[i][j].numpy())  # In TensorFlow 2.x, use .numpy() to get the value from the tensor

Iterate through Tensor 'a':
2.0
1.0
1.0
0.0


In [ ]:
# Define tensor constants.
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(5)

In [ ]:
# Various tensor operations.
# Note: Tensors also support python operators (+, *, ...)
add = tf.add(a, b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a, b)

# Access tensors value.
print("add =", add.numpy())
print("sub =", sub.numpy())
print("mul =", mul.numpy())
print("div =", div.numpy())

add = 5
sub = -1
mul = 6
div = 0.6666666666666666


In [ ]:
# Some more operations.
mean = tf.reduce_mean([a, b, c])
sum = tf.reduce_sum([a, b, c])

# Access tensors value.
print("mean =", mean.numpy())
print("sum =", sum.numpy())

mean = 3
sum = 10


In [ ]:
# Matrix multiplications.
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[5., 6.], [7., 8.]])

product = tf.matmul(matrix1, matrix2)
product.shape

TensorShape([2, 2])

In [ ]:
# Convert Tensor to Numpy.
product.numpy()

array([[19., 22.],
       [43., 50.]], dtype=float32)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!apt-get install git


Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.11).
0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.


In [ ]:
!git config --global user.name "yuvrajpant"
!git config --global user.email "yuvrajpant5@gmail.com"

In [ ]:
!git clone https://github.com/yuvrajpant56/Tensor_Flow_Introduction.git


Cloning into 'Tensor_Flow_Introduction'...


In [ ]:
%cd Tensor_Flow_Introduction/

/content/Tensor_Flow_Introduction/Tensor_Flow_Introduction/Tensor_Flow_Introduction/Tensor_Flow_Introduction


In [ ]:
!cp /content/drive/MyDrive/Introduction_TesorFlow_Operation/TensorFlow_Eager_API.ipynb .

In [ ]:
!git add TensorFlow_Eager_API.ipynb

In [ ]:
!git commit -m "added TensorFLOW OPERATIONS"

[main (root-commit) f6e633c] added TensorFLOW OPERATIONS
 1 file changed, 1 insertion(+)
 create mode 100644 TensorFlow_Eager_API.ipynb


In [ ]:
!git push origin main  # Use 'master' if your default branch is 'master'


error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/yuvrajpant56/Tensor_Flow_Introduction.git'


In [ ]:
!rm -r Tensor_Flow_Introduction


rm: cannot remove 'Tensor_Flow_Introduction': No such file or directory


In [ ]:
%cd ../


/content/Tensor_Flow_Introduction/Tensor_Flow_Introduction/Tensor_Flow_Introduction


In [ ]:
%cd ../..


/content/Tensor_Flow_Introduction


In [ ]:
!rm -r Tensor_Flow_Introduction/

In [ ]:
%ls

In [ ]:
%pid

UsageError: Line magic function `%pid` not found.


In [ ]:
%PID

UsageError: Line magic function `%PID` not found.


In [68]:
%cd ..

/content


In [69]:
% cd content/

UsageError: Line magic function `%` not found.


In [70]:
%cd content/

[Errno 2] No such file or directory: 'content/'
/content


In [71]:
%cd /content/

/content


In [72]:
%ls

drive/  TensorFlow_Eager_API.ipynb  Tensor_Flow_Introduction/


In [73]:
%cd /content/drive/

/content/drive


In [74]:
!rm -r Tensor_Flow_Introduction

rm: cannot remove 'Tensor_Flow_Introduction': No such file or directory


In [75]:
%ls

MyDrive/


In [76]:
%cd ..

/content


In [77]:
!rm -r Tensor_Flow_Introduction/

In [78]:
%cd /content/drive/

/content/drive


In [79]:
%ls

MyDrive/


In [83]:
!apt-get install git

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.11).
0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.


In [84]:
!git config --global user.name "yuvrajpant56"
!git config --global user.email "yuvrajpant5@gmail.com"


In [85]:
!git clone https://github.com/yuvrajpant56/Tensor_Flow_Introduction.git

fatal: could not create work tree dir 'Tensor_Flow_Introduction': Operation not supported


In [86]:
%cd ..

/content


In [87]:
!apt-get install git

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.11).
0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.


In [88]:
!git config --global user.name "yuvrajpant56"
!git config --global user.email "yuvrajpant5@gmail.com"

In [89]:
!git clone https://github.com/yuvrajpant56/Tensor_Flow_Introduction.git

Cloning into 'Tensor_Flow_Introduction'...


In [90]:
%cd Tensor_Flow_Introduction/

/content/Tensor_Flow_Introduction


In [ ]:
!cp /content/drive/MyDrive/